/**
 * MotionBro — Scripts incluidos en la extension (scripts/bundled/).
 * Al empaquetar ZXP viajan dentro del plugin; no dependen de rutas externas.
 */
(function (global) {
  'use strict';

  var DEFAULT_SCRIPTS = [
    { id: 1, name: 'Alinear Capas', description: 'Alinea todas las capas seleccionadas al inicio de la composición o a un punto específico.', category: 'layers', isFav: false, code: '', bundledFile: 'Alinear Capas al Inicio.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><line x1="4" y1="21" x2="4" y2="3"></line><line x1="8" y1="6" x2="18" y2="6"></line><line x1="8" y1="12" x2="14" y2="12"></line><line x1="8" y1="18" x2="20" y2="18"></line></svg>' },
    { id: 3, name: 'Colorizar Capas', description: 'Asigna colores de etiqueta aleatorios o específicos a las capas seleccionadas.', category: 'layers', isFav: false, code: '', bundledFile: 'Colorizar Capas Auto.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"></path></svg>' },
    { id: 4, name: 'Copiar y Pegar Fotogramas', description: 'Copia los fotogramas clave y los pega en múltiples capas conservando el ritmo.', category: 'animation', isFav: false, code: '', bundledFile: 'Copiar y Pegar Fotogramas.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>' },
    { id: 5, name: 'Copiar y Pegar Invertido', description: 'Copia fotogramas y los pega con el orden temporal invertido de forma automática.', category: 'animation', isFav: false, code: '', bundledFile: 'Copiar y Pegar Invertido.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="9" y="9" width="13" height="13" rx="2" ry="2" stroke-dasharray="2 2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path><line x1="10" y1="15" x2="14" y2="15"></line></svg>' },
    { id: 6, name: 'Crear Capas Fotogramas', description: 'Corta las capas activas exactamente donde tienen fotogramas clave.', category: 'layers', isFav: false, code: '', bundledFile: 'Cortar Capas a Fotogramas.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>' },
    { id: 7, name: 'Crear Nulo Desde Capas', description: 'Crea un objeto nulo exactamente en el centro de todas las capas seleccionadas.', category: 'layers', isFav: false, code: '', bundledFile: 'Crear Nulo Central.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="3" y="3" width="18" height="18" rx="2" ry="2" stroke-dasharray="4 4"></rect><circle cx="12" cy="12" r="2"></circle><polyline points="3 9 7 9 7 3"></polyline><polyline points="21 15 17 15 17 21"></polyline></svg>' },
    { id: 8, name: 'Des-precomponer Capas', description: 'Extrae todas las capas de una precomposición hacia tu línea de tiempo actual.', category: 'layers', isFav: false, code: '', bundledFile: 'Des-precomponer Capas.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 12 12 17 22 12"></polyline><line x1="12" y1="22" x2="12" y2="12"></line><polyline points="9 19 12 22 15 19"></polyline></svg>' },
    { id: 10, name: 'Duplicar Comps Dependientes', description: 'Duplica una composición asegurando que sus precomposiciones internas también sean independientes.', category: 'utilities', isFav: false, code: '', bundledFile: 'Duplicar Comp Independiente.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="2" y="2" width="14" height="14" rx="2" ry="2"></rect><rect x="8" y="8" width="14" height="14" rx="2" ry="2"></rect></svg>' },
    { id: 13, name: 'FX Fotogramas Alineación', description: 'Alinea los fotogramas clave de los efectos al punto de inicio.', category: 'animation', isFav: false, code: '', bundledFile: 'FTG Fotogramas al Inicio.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><text x="12" y="16" font-family="Arial" font-size="14" font-weight="bold" font-style="italic" text-anchor="middle" fill="currentColor" stroke="none">fx</text></svg>' },
    { id: 14, name: 'Importar Subtítulos SRT', description: 'Importa un archivo SRT y crea capas de texto para generar subtítulos automáticos.', category: 'utilities', isFav: false, code: '', bundledFile: 'Importar Subtitulos SRT.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><rect x="2" y="4" width="20" height="16" rx="2" ry="2"></rect><path d="M7 15h3M14 15h3M7 9h10"></path></svg>' },
    { id: 15, name: 'Recortar Precomps', description: 'Recorta las precomposiciones basándose en la duración de las capas que contienen.', category: 'utilities', isFav: false, code: '', bundledFile: 'Recortar Precomp.jsxbin', icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M6.13 1L6 16a2 2 0 0 0 2 2h15"></path><path d="M1 6.13L16 6a2 2 0 0 1 2 2v15"></path></svg>' }
  ];

  global.MotionBroScriptsData = {
    defaults: DEFAULT_SCRIPTS
  };
})(typeof window !== 'undefined' ? window : global);
